services:
    extension.tickets:
        class: App\Extension\TicketCollectionExtension
        public: false
        arguments:
            - '@request_stack'
        tags:
            - { name: api_platform.doctrine.orm.query_extension.collection, priority: 9 }

    App\Subscriber\TicketApiSubscriber:
        arguments:
            - '@security.token_storage'
        tags:
            - { name: kernel.event_subscriber }

    App\Subscriber\UserSubscriber:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@security.user_password_encoder.generic'
        tags:
            - { name: kernel.event_subscriber }